"""Create essential oils table with safe usage rates and blending guidance

Revision ID: 005
Revises: 004
Create Date: 2025-11-05 08:15:00

This migration creates the essential_oils table for safe essential oil usage:
- 39 essential oils with CPSR-validated maximum usage rates
- Scent profiles and fragrance notes (top/middle/base)
- Blending recommendations with complementary oils
- Safety warnings for skin sensitivity, photosensitivity, etc.

Essential oils have strict maximum usage rates to ensure CPSR compliance
and skin safety. Rates range from 0.025% to 3.0% of batch weight.
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects.postgresql import ARRAY

# revision identifiers, used by Alembic.
revision: str = '005'
down_revision: Union[str, None] = '004'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Create essential_oils table with safety and blending data"""

    op.create_table(
        'essential_oils',
        sa.Column(
            'id',
            sa.String(50),
            primary_key=True,
            comment='Unique identifier (slug format: lavender-40-42, peppermint)'
        ),
        sa.Column(
            'common_name',
            sa.String(100),
            nullable=False,
            comment='Common English name (e.g., Lavender 40/42, Peppermint)'
        ),
        sa.Column(
            'botanical_name',
            sa.String(200),
            nullable=True,
            comment='Scientific botanical name for precise identification'
        ),
        sa.Column(
            'inci_name',
            sa.String(200),
            nullable=True,
            comment='INCI (International Nomenclature of Cosmetic Ingredients) name'
        ),
        sa.Column(
            'max_usage_rate_pct',
            sa.Numeric(precision=5, scale=3),
            nullable=False,
            comment='Maximum safe usage rate as percentage of batch weight (0.025 to 3.0)'
        ),
        sa.Column(
            'scent_profile',
            sa.String(500),
            nullable=True,
            comment='Descriptive scent characteristics'
        ),
        sa.Column(
            'note',
            sa.String(20),
            nullable=True,
            comment='Fragrance note: top, middle, or base'
        ),
        sa.Column(
            'blends_with',
            ARRAY(sa.String),
            nullable=True,
            comment='List of essential oil IDs that blend well with this oil'
        ),
        sa.Column(
            'category',
            sa.String(50),
            nullable=True,
            comment='Scent category: citrus, floral, herbaceous, woody, spicy, etc.'
        ),
        sa.Column(
            'warnings',
            ARRAY(sa.String),
            nullable=True,
            comment='Safety warnings: fades quickly, accelerates trace, skin sensitivity, photosensitivity'
        ),
        sa.Column(
            'created_at',
            sa.DateTime(timezone=True),
            nullable=False,
            server_default=sa.func.now(),
            comment='UTC timestamp generated by PostgreSQL server'
        ),
        sa.Column(
            'updated_at',
            sa.DateTime(timezone=True),
            nullable=False,
            server_default=sa.func.now(),
            comment='UTC timestamp auto-updated by PostgreSQL trigger'
        )
    )

    # Add CHECK constraint for max usage rate range (0.025% to 3.0%)
    op.create_check_constraint(
        'check_essential_oil_max_usage_rate_range',
        'essential_oils',
        'max_usage_rate_pct >= 0.025 AND max_usage_rate_pct <= 3.0'
    )

    # Add CHECK constraint for valid fragrance notes
    op.create_check_constraint(
        'check_essential_oil_note_valid',
        'essential_oils',
        "note IS NULL OR note IN ('top', 'middle', 'base')"
    )

    # Add index on common_name for search
    op.create_index(
        'ix_essential_oils_common_name',
        'essential_oils',
        ['common_name']
    )

    # Add index on category for filtering
    op.create_index(
        'ix_essential_oils_category',
        'essential_oils',
        ['category']
    )

    # Add index on note for fragrance blending queries
    op.create_index(
        'ix_essential_oils_note',
        'essential_oils',
        ['note']
    )

    # Create trigger for auto-updating updated_at timestamp
    op.execute(
        """
        CREATE OR REPLACE FUNCTION update_essential_oils_updated_at()
        RETURNS TRIGGER AS $$
        BEGIN
            NEW.updated_at = NOW();
            RETURN NEW;
        END;
        $$ LANGUAGE plpgsql;
        """
    )

    op.execute(
        """
        CREATE TRIGGER trigger_update_essential_oils_updated_at
        BEFORE UPDATE ON essential_oils
        FOR EACH ROW
        EXECUTE FUNCTION update_essential_oils_updated_at();
        """
    )


def downgrade() -> None:
    """Drop essential_oils table and related objects"""

    # Drop trigger and function
    op.execute('DROP TRIGGER IF EXISTS trigger_update_essential_oils_updated_at ON essential_oils')
    op.execute('DROP FUNCTION IF EXISTS update_essential_oils_updated_at()')

    # Drop indexes
    op.drop_index('ix_essential_oils_note', table_name='essential_oils')
    op.drop_index('ix_essential_oils_category', table_name='essential_oils')
    op.drop_index('ix_essential_oils_common_name', table_name='essential_oils')

    # Drop CHECK constraints
    op.drop_constraint('check_essential_oil_note_valid', 'essential_oils', type_='check')
    op.drop_constraint('check_essential_oil_max_usage_rate_range', 'essential_oils', type_='check')

    # Drop table
    op.drop_table('essential_oils')
