"""Create colorants table with natural soap colorants and usage guidance

Revision ID: 006
Revises: 005
Create Date: 2025-11-05 08:30:00

This migration creates the colorants table for natural soap coloring:
- 79 natural colorants across 7 color families
- Includes clays, botanicals, powders, and infused oils
- Color range descriptions and application methods
- Usage rate guidance and preparation techniques
- Warnings for fading, staining, scratchy textures, etc.

Natural colorants provide alternatives to synthetic dyes with
varying color stability and application techniques.
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "006"
down_revision: str | None = "005"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Create colorants table with natural colorant data"""

    op.create_table(
        "colorants",
        sa.Column(
            "id",
            sa.String(50),
            primary_key=True,
            comment="Unique identifier (slug format: turmeric, spirulina, madder-root)",
        ),
        sa.Column(
            "name",
            sa.String(100),
            nullable=False,
            comment="Colorant name (e.g., Turmeric, Spirulina, Madder Root)",
        ),
        sa.Column(
            "botanical_name",
            sa.String(200),
            nullable=True,
            comment="Scientific botanical name if plant-derived",
        ),
        sa.Column(
            "color_category",
            sa.String(50),
            nullable=False,
            comment="Color family: yellow, orange, pink, red, purple, blue, brown, green, white, black",
        ),
        sa.Column(
            "usage_rate",
            sa.String(200),
            nullable=True,
            comment="Usage rate guidance: 1-3 tsp per pound, 1 tablespoon per batch, infuse at 1:10 ratio",
        ),
        sa.Column(
            "method",
            sa.String(200),
            nullable=True,
            comment="Application method: infuse in oil, add to lye water, disperse at trace, powder form",
        ),
        sa.Column(
            "color_range_description",
            sa.String(500),
            nullable=True,
            comment="Color range achievable: pale yellow to burnt orange, soft pink to deep rose",
        ),
        sa.Column(
            "warnings",
            sa.String(500),
            nullable=True,
            comment="Usage warnings: fades with time, can be scratchy, stains, turns brown, reacts with fragrance",
        ),
        sa.Column(
            "notes",
            sa.String(500),
            nullable=True,
            comment="Additional notes: best for melt and pour, CP soap safe, works well with white base",
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            nullable=False,
            server_default=sa.func.now(),
            comment="UTC timestamp generated by PostgreSQL server",
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            nullable=False,
            server_default=sa.func.now(),
            comment="UTC timestamp auto-updated by PostgreSQL trigger",
        ),
    )

    # Add CHECK constraint for valid color categories
    op.create_check_constraint(
        "check_colorant_color_category_valid",
        "colorants",
        "color_category IN ('yellow', 'orange', 'pink', 'red', 'purple', 'blue', 'brown', 'green', 'white', 'black')",
    )

    # Add index on color_category for filtering by color
    op.create_index("ix_colorants_color_category", "colorants", ["color_category"])

    # Add index on name for search
    op.create_index("ix_colorants_name", "colorants", ["name"])

    # Create trigger for auto-updating updated_at timestamp
    op.execute(
        """
        CREATE OR REPLACE FUNCTION update_colorants_updated_at()
        RETURNS TRIGGER AS $$
        BEGIN
            NEW.updated_at = NOW();
            RETURN NEW;
        END;
        $$ LANGUAGE plpgsql;
        """
    )

    op.execute(
        """
        CREATE TRIGGER trigger_update_colorants_updated_at
        BEFORE UPDATE ON colorants
        FOR EACH ROW
        EXECUTE FUNCTION update_colorants_updated_at();
        """
    )


def downgrade() -> None:
    """Drop colorants table and related objects"""

    # Drop trigger and function
    op.execute("DROP TRIGGER IF EXISTS trigger_update_colorants_updated_at ON colorants")
    op.execute("DROP FUNCTION IF EXISTS update_colorants_updated_at()")

    # Drop indexes
    op.drop_index("ix_colorants_name", table_name="colorants")
    op.drop_index("ix_colorants_color_category", table_name="colorants")

    # Drop CHECK constraint
    op.drop_constraint("check_colorant_color_category_valid", "colorants", type_="check")

    # Drop table
    op.drop_table("colorants")
