"""Additive model with quality effect modifiers"""
from datetime import datetime
from decimal import Decimal
from typing import Optional

import sqlalchemy as sa
from sqlalchemy import String, Float, Boolean, DateTime, Numeric
from sqlalchemy.dialects.postgresql import JSONB
from sqlalchemy.orm import Mapped, mapped_column

from app.db.base import Base


class Additive(Base):
    """
    Non-fat additive that modifies soap quality metrics.

    Includes clays, salts, botanicals, proteins, and sugars.
    Effects are absolute modifiers calculated at 2% usage rate.
    """

    __tablename__ = "additives"

    id: Mapped[str] = mapped_column(
        String(100),  # Increased from 50 to handle long names
        primary_key=True,
    )
    common_name: Mapped[str] = mapped_column(
        String(100),
        nullable=False,
    )
    inci_name: Mapped[str] = mapped_column(
        String(200),
        nullable=False,
    )
    typical_usage_min_percent: Mapped[float] = mapped_column(
        Float,
        nullable=False,
        comment="Minimum recommended usage as % of oil weight",
    )
    typical_usage_max_percent: Mapped[float] = mapped_column(
        Float,
        nullable=False,
        comment="Maximum recommended usage as % of oil weight",
    )
    quality_effects: Mapped[dict] = mapped_column(
        JSONB,
        nullable=False,
        comment="Absolute modifiers to quality metrics at 2% usage. Scale proportionally for other usage rates.",
    )
    confidence_level: Mapped[str] = mapped_column(
        String(20),
        nullable=False,
        comment="Research confidence: high, medium, low",
    )
    verified_by_mga: Mapped[bool] = mapped_column(
        Boolean,
        nullable=False,
        default=False,
        comment="Whether MGA has empirically validated effects",
    )
    safety_warnings: Mapped[Optional[dict]] = mapped_column(
        JSONB,
        nullable=True,
        comment="Optional safety information and usage notes",
    )
    # Smart calculator fields
    usage_rate_min_pct: Mapped[Optional[Decimal]] = mapped_column(
        Numeric(5, 2),
        nullable=True,
        comment="Minimum usage percentage for calculator (light usage)",
    )
    usage_rate_max_pct: Mapped[Optional[Decimal]] = mapped_column(
        Numeric(5, 2),
        nullable=True,
        comment="Maximum usage percentage for calculator (heavy usage)",
    )
    usage_rate_standard_pct: Mapped[Optional[Decimal]] = mapped_column(
        Numeric(5, 2),
        nullable=True,
        comment="Standard recommended usage percentage for calculator",
    )
    when_to_add: Mapped[Optional[str]] = mapped_column(
        String(200),
        nullable=True,
        comment="Timing guidance: to oils, to lye water, at trace, etc.",
    )
    preparation_instructions: Mapped[Optional[str]] = mapped_column(
        String(500),
        nullable=True,
        comment="How to prepare additive before incorporation",
    )
    category: Mapped[Optional[str]] = mapped_column(
        String(50),
        nullable=True,
        comment="Additive category: exfoliant, colorant, lather_booster, hardener, clay, botanical",
    )
    warnings: Mapped[Optional[dict]] = mapped_column(
        JSONB,
        nullable=True,
        comment="Specific warnings: accelerates_trace, causes_overheating, can_be_scratchy, turns_brown",
    )
    created_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True),
        nullable=False,
        server_default=sa.func.now(),
        comment="UTC timestamp generated by PostgreSQL server",
    )
    updated_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True),
        nullable=False,
        server_default=sa.func.now(),
        comment="UTC timestamp auto-updated by PostgreSQL trigger",
    )

    def __repr__(self) -> str:
        return f"<Additive(id={self.id}, name={self.common_name}, confidence={self.confidence_level})>"
