"""Calculation model for storing recipe calculations"""
import uuid
from datetime import datetime
from decimal import Decimal
from typing import Optional

import sqlalchemy as sa
from sqlalchemy import ForeignKey, DateTime, Numeric
from sqlalchemy.dialects.postgresql import UUID, JSONB
from sqlalchemy.orm import Mapped, mapped_column, relationship

from app.db.base import Base


class Calculation(Base):
    """
    Stored soap recipe calculation with complete input and output data.

    Links to user for ownership.
    Stores complete recipe and results as JSONB for flexibility.
    """

    __tablename__ = "calculations"

    id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True),
        primary_key=True,
        default=uuid.uuid4,
    )
    user_id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True),
        ForeignKey("users.id", ondelete="CASCADE"),
        nullable=False,
        index=True,
    )
    recipe_data: Mapped[dict] = mapped_column(
        JSONB,
        nullable=False,
        comment="Complete recipe input: oils, lye, water, superfat, additives",
    )
    results_data: Mapped[dict] = mapped_column(
        JSONB,
        nullable=False,
        comment="Complete calculation results: quality metrics, fatty acids, effects",
    )
    created_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True),
        nullable=False,
        server_default=sa.func.now(),
        index=True,
        comment="UTC timestamp generated by PostgreSQL server",
    )

    # Purity tracking (Feature 002: KOH/NaOH Purity Support)
    koh_purity: Mapped[Decimal] = mapped_column(
        Numeric(5, 2),
        nullable=False,
        server_default="90.00",
        index=True,
        comment="KOH purity percentage (50-100). Default 90% reflects commercial grade.",
    )
    naoh_purity: Mapped[Decimal] = mapped_column(
        Numeric(5, 2),
        nullable=False,
        server_default="100.00",
        comment="NaOH purity percentage (50-100). Default 100% reflects commercial grade.",
    )
    pure_koh_equivalent_g: Mapped[Optional[Decimal]] = mapped_column(
        Numeric(10, 2),
        nullable=True,
        comment="Theoretical pure KOH amount before purity adjustment",
    )
    pure_naoh_equivalent_g: Mapped[Optional[Decimal]] = mapped_column(
        Numeric(10, 2),
        nullable=True,
        comment="Theoretical pure NaOH amount before purity adjustment",
    )
    purity_assumed: Mapped[bool] = mapped_column(
        sa.Boolean,
        nullable=False,
        server_default="false",
        index=True,
        comment="True if purity was assumed (legacy recipe), false if explicitly set",
    )

    # Relationship to user
    user: Mapped["User"] = relationship(
        "User",
        back_populates="calculations",
    )

    def __repr__(self) -> str:
        return f"<Calculation(id={self.id}, user_id={self.user_id})>"
