"""Colorant model with natural soap colorants and usage guidance"""
from datetime import datetime
from typing import Optional

import sqlalchemy as sa
from sqlalchemy import String, DateTime
from sqlalchemy.orm import Mapped, mapped_column

from app.db.base import Base


class Colorant(Base):
    """
    Natural colorant for soap with color characteristics and usage methods.

    Includes clays, botanicals, powders, and infused oils.
    79 natural colorants across 7 color families.
    """

    __tablename__ = "colorants"

    id: Mapped[str] = mapped_column(
        String(50),
        primary_key=True,
    )
    name: Mapped[str] = mapped_column(
        String(100),
        nullable=False,
    )
    botanical_name: Mapped[Optional[str]] = mapped_column(
        String(200),
        nullable=True,
        comment="Scientific botanical name if plant-derived",
    )
    color_category: Mapped[str] = mapped_column(
        String(50),
        nullable=False,
        comment="Color family: yellow, orange, pink, red, purple, blue, brown, green, white, black",
    )
    usage_rate: Mapped[Optional[str]] = mapped_column(
        String(200),
        nullable=True,
        comment="Usage rate guidance: 1-3 tsp per pound, 1 tablespoon per batch, infuse at 1:10 ratio",
    )
    method: Mapped[Optional[str]] = mapped_column(
        String(200),
        nullable=True,
        comment="Application method: infuse in oil, add to lye water, disperse at trace, powder form",
    )
    color_range_description: Mapped[Optional[str]] = mapped_column(
        String(500),
        nullable=True,
        comment="Color range achievable: pale yellow to burnt orange, soft pink to deep rose",
    )
    warnings: Mapped[Optional[str]] = mapped_column(
        String(500),
        nullable=True,
        comment="Usage warnings: fades with time, can be scratchy, stains, turns brown, reacts with fragrance",
    )
    notes: Mapped[Optional[str]] = mapped_column(
        String(500),
        nullable=True,
        comment="Additional notes: best for melt and pour, CP soap safe, works well with white base",
    )
    created_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True),
        nullable=False,
        server_default=sa.func.now(),
        comment="UTC timestamp generated by PostgreSQL server",
    )
    updated_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True),
        nullable=False,
        server_default=sa.func.now(),
        comment="UTC timestamp auto-updated by PostgreSQL trigger",
    )

    def __repr__(self) -> str:
        return f"<Colorant(id={self.id}, name={self.name}, color={self.color_category})>"
