"""Essential oil model with safe usage rates and blending guidance"""
from datetime import datetime
from decimal import Decimal
from typing import Optional

import sqlalchemy as sa
from sqlalchemy import String, DateTime, Numeric, Text
from sqlalchemy.dialects.postgresql import ARRAY
from sqlalchemy.orm import Mapped, mapped_column

from app.db.base import Base


class EssentialOil(Base):
    """
    Essential oil with maximum safe usage rates and scent characteristics.

    Includes CPSR-validated usage rates, scent profiles, and blending guidance.
    39 essential oils with safety data and olfactory properties.
    """

    __tablename__ = "essential_oils"

    id: Mapped[str] = mapped_column(
        String(50),
        primary_key=True,
    )
    common_name: Mapped[str] = mapped_column(
        String(100),
        nullable=False,
    )
    botanical_name: Mapped[Optional[str]] = mapped_column(
        String(200),
        nullable=True,
        comment="Scientific botanical name for precise identification",
    )
    inci_name: Mapped[Optional[str]] = mapped_column(
        String(200),
        nullable=True,
        comment="INCI (International Nomenclature of Cosmetic Ingredients) name",
    )
    max_usage_rate_pct: Mapped[Decimal] = mapped_column(
        Numeric(5, 3),
        nullable=False,
        comment="Maximum safe usage rate as percentage of batch weight (0.025 to 3.0)",
    )
    scent_profile: Mapped[Optional[str]] = mapped_column(
        String(500),
        nullable=True,
        comment="Descriptive scent characteristics",
    )
    usage_notes: Mapped[Optional[str]] = mapped_column(
        Text,
        nullable=True,
        comment="Usage guidance and historical context",
    )
    note: Mapped[Optional[str]] = mapped_column(
        String(50),  # Increased from 20 to handle longer notes
        nullable=True,
        comment="Fragrance note: top, middle, or base",
    )
    blends_with: Mapped[Optional[list]] = mapped_column(
        ARRAY(String),
        nullable=True,
        comment="List of essential oil IDs that blend well with this oil",
    )
    category: Mapped[Optional[str]] = mapped_column(
        String(50),
        nullable=True,
        comment="Scent category: citrus, floral, herbaceous, woody, spicy, etc.",
    )
    warnings: Mapped[Optional[str]] = mapped_column(
        String(500),
        nullable=True,
        comment="Safety warnings: fades quickly, accelerates trace, skin sensitivity, photosensitivity",
    )
    color_effect: Mapped[Optional[str]] = mapped_column(
        String(200),
        nullable=True,
        comment="Expected color impact on soap",
    )
    created_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True),
        nullable=False,
        server_default=sa.func.now(),
        comment="UTC timestamp generated by PostgreSQL server",
    )
    updated_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True),
        nullable=False,
        server_default=sa.func.now(),
        comment="UTC timestamp auto-updated by PostgreSQL trigger",
    )

    def __repr__(self) -> str:
        return f"<EssentialOil(id={self.id}, name={self.common_name}, max_rate={self.max_usage_rate_pct}%)>"
