"""Oil model with SAP values and fatty acid profiles"""

from datetime import datetime

import sqlalchemy as sa
from sqlalchemy import DateTime, Float, String
from sqlalchemy.dialects.postgresql import JSONB
from sqlalchemy.orm import Mapped, mapped_column

from app.db.base import Base


class Oil(Base):
    """
    Oil/fat ingredient with saponification values and properties.

    SAP values define grams of lye needed per gram of oil.
    Fatty acid profile determines soap quality characteristics.
    Saponified INCI name represents post-saponification nomenclature.
    """

    __tablename__ = "oils"

    id: Mapped[str] = mapped_column(
        String(50),
        primary_key=True,
    )
    common_name: Mapped[str] = mapped_column(
        String(100),
        nullable=False,
    )
    inci_name: Mapped[str] = mapped_column(
        String(200),
        nullable=False,
    )
    saponified_inci_name: Mapped[str | None] = mapped_column(
        String(200),
        nullable=True,
        comment="Post-saponification INCI name (e.g., 'Sodium Cocoate' or 'Potassium Cocoate')",
    )
    sap_value_naoh: Mapped[float] = mapped_column(
        Float,
        nullable=False,
        comment="Grams NaOH per gram of oil",
    )
    sap_value_koh: Mapped[float] = mapped_column(
        Float,
        nullable=False,
        comment="Grams KOH per gram of oil",
    )
    iodine_value: Mapped[float] = mapped_column(
        Float,
        nullable=False,
        comment="Measure of unsaturation",
    )
    ins_value: Mapped[float] = mapped_column(
        Float,
        nullable=False,
        comment="Iodine Number Saponification (hardness indicator)",
    )
    fatty_acids: Mapped[dict] = mapped_column(
        JSONB,
        nullable=False,
        comment="Percentages of 8 fatty acids: lauric, myristic, palmitic, stearic, ricinoleic, oleic, linoleic, linolenic",  # noqa: E501
    )
    quality_contributions: Mapped[dict] = mapped_column(
        JSONB,
        nullable=False,
        comment="Contribution to 7 quality metrics: hardness, cleansing, conditioning, bubbly_lather, creamy_lather, longevity, stability",  # noqa: E501
    )
    created_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True),
        nullable=False,
        server_default=sa.func.now(),
        comment="UTC timestamp generated by PostgreSQL server",
    )
    updated_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True),
        nullable=False,
        server_default=sa.func.now(),
        comment="UTC timestamp auto-updated by PostgreSQL trigger",
    )

    def __repr__(self) -> str:
        return f"<Oil(id={self.id}, name={self.common_name})>"
