"""User model for authentication and calculation ownership"""

import uuid
from datetime import datetime

import sqlalchemy as sa
from sqlalchemy import DateTime, String
from sqlalchemy.dialects.postgresql import UUID
from sqlalchemy.orm import Mapped, mapped_column, relationship, validates

from app.db.base import Base


class User(Base):
    """User model with UUID primary key

    SECURITY: Password must be Argon2id-hashed before assignment.
    Use app.core.security.get_password_hash() to hash passwords.
    The hashed_password field validates Argon2id format on assignment.
    """

    __tablename__ = "users"

    id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True),
        primary_key=True,
        default=uuid.uuid4,
    )
    email: Mapped[str] = mapped_column(
        String(255),
        unique=True,
        nullable=False,
        index=True,
    )
    hashed_password: Mapped[str] = mapped_column(
        String(255),
        nullable=False,
        comment="MUST be Argon2id hash format ($argon2id$ prefix). Use app.core.security.get_password_hash() to hash passwords.",  # noqa: E501
    )

    @validates("hashed_password")
    def validate_hashed_password(self, key, value):
        """Validate that password is properly Argon2id-hashed

        Prevents accidental plaintext password storage by verifying
        Argon2id hash format ($argon2id$ prefix with proper structure).

        Args:
            key: Column name (hashed_password)
            value: Password string to validate

        Returns:
            Validated password hash

        Raises:
            ValueError: If password is not a valid Argon2id hash
        """
        # Allow None during model construction (will fail nullable constraint)
        if value is None:
            return value

        # Verify Argon2id hash format
        # Argon2id hashes start with $argon2id$ followed by version and parameters
        if not value.startswith("$argon2id$"):
            raise ValueError(
                "Password must be Argon2id-hashed before assignment. "
                "Use app.core.security.get_password_hash('your_password') to hash passwords. "
                f"Got value starting with: {value[:20] if len(value) >= 20 else value}"
            )

        # Verify it's at least the minimum length for an Argon2id hash (~90 chars)
        if len(value) < 80:
            raise ValueError(
                f"Invalid Argon2id hash format - too short (got {len(value)} chars, expected ≥80). "
                "Use app.core.security.get_password_hash() to generate proper Argon2id hashes."
            )

        return value

    created_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True),
        nullable=False,
        server_default=sa.func.now(),
        comment="UTC timestamp generated by PostgreSQL server",
    )
    updated_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True),
        nullable=False,
        server_default=sa.func.now(),
        comment="UTC timestamp auto-updated by PostgreSQL trigger",
    )

    # Relationship to calculations
    calculations: Mapped[list["Calculation"]] = relationship(
        "Calculation",
        back_populates="user",
        cascade="all, delete-orphan",
    )

    def __repr__(self) -> str:
        return f"<User(id={self.id}, email={self.email})>"
