"""User model for authentication and calculation ownership"""
import uuid
from datetime import datetime

import sqlalchemy as sa
from sqlalchemy import String, DateTime
from sqlalchemy.dialects.postgresql import UUID
from sqlalchemy.orm import Mapped, mapped_column, relationship, validates
from passlib.hash import bcrypt

from app.db.base import Base


class User(Base):
    """User model with UUID primary key

    SECURITY: Password must be bcrypt-hashed before assignment.
    Use passlib.hash.bcrypt.hash() to hash passwords.
    The hashed_password field validates bcrypt format on assignment.
    """

    __tablename__ = "users"

    id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True),
        primary_key=True,
        default=uuid.uuid4,
    )
    email: Mapped[str] = mapped_column(
        String(255),
        unique=True,
        nullable=False,
        index=True,
    )
    hashed_password: Mapped[str] = mapped_column(
        String(255),
        nullable=False,
        comment="MUST be bcrypt hash format ($2b$ prefix). Use passlib.hash.bcrypt.hash() to hash passwords.",
    )

    @validates('hashed_password')
    def validate_hashed_password(self, key, value):
        """Validate that password is properly bcrypt-hashed

        Prevents accidental plaintext password storage by verifying
        bcrypt hash format ($2a$, $2b$, or $2y$ prefix with proper structure).

        Args:
            key: Column name (hashed_password)
            value: Password string to validate

        Returns:
            Validated password hash

        Raises:
            ValueError: If password is not a valid bcrypt hash
        """
        # Allow None during model construction (will fail nullable constraint)
        if value is None:
            return value

        # Verify bcrypt hash format
        # bcrypt hashes start with $2a$, $2b$, or $2y$ followed by cost and salt
        if not value.startswith(('$2a$', '$2b$', '$2y$')):
            raise ValueError(
                "Password must be bcrypt-hashed before assignment. "
                "Use passlib.hash.bcrypt.hash('your_password') to hash passwords. "
                f"Got value starting with: {value[:10] if len(value) >= 10 else value}"
            )

        # Verify it's at least the minimum length for a bcrypt hash (~60 chars)
        if len(value) < 59:
            raise ValueError(
                f"Invalid bcrypt hash format - too short (got {len(value)} chars, expected ≥59). "
                "Use passlib.hash.bcrypt.hash() to generate proper bcrypt hashes."
            )

        return value
    created_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True),
        nullable=False,
        server_default=sa.func.now(),
        comment="UTC timestamp generated by PostgreSQL server",
    )
    updated_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True),
        nullable=False,
        server_default=sa.func.now(),
        comment="UTC timestamp auto-updated by PostgreSQL trigger",
    )

    # Relationship to calculations
    calculations: Mapped[list["Calculation"]] = relationship(
        "Calculation",
        back_populates="user",
        cascade="all, delete-orphan",
    )

    def __repr__(self) -> str:
        return f"<User(id={self.id}, email={self.email})>"
